name: conchayoro-pipeline

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
      with:
        name: ebconfig
        path: |
            backend/.elasticbeanstalk/config.yml
            backend/Dockerrun.aws.json

    - name: setup node
      uses: actions/setup-node@v3
      with:
        node-version: '16'
        cache: 'npm'
  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/download-artifact@v3
      with:
        name: ebconfig
        path: .
      - run: |
            sed -i='' "s/<AWS_ACCOUNT_ID>/$AWS_ACCOUNT_ID/" Dockerrun.aws.json
            sed -i='' "s/<PROJECT_NAME>/$PROJECT_NAME/" Dockerrun.aws.json
            sed -i='' "s/<MODULE_NAME>/$MODULE_NAME/" Dockerrun.aws.json
            sed -i='' "s/<TAG>/$TAG/" Dockerrun.aws.json
      - uses: actions/setup-python@v2
        with:
          python-version: '3.10'
      - run: |
          python -m pip install --upgrade pip
          pip install awsebcli
      - run: |
          eb deploy --verbose